seed: 42
device: "cuda"   # or "cpu"
save_dir: "outputs"

data:
  root: "./data"
  batch_size: 128
  num_workers: 2

model:
  in_channels: 1
  hidden_channels: 64
  time_embed_dim: 64

train:
  epochs: 5
  lr: 1e-3
  log_interval: 100
  sample_every_epochs: 1

sampler:
  steps: 50         # Euler steps
  sample_batch: 64
